theme: tailwind-starter
languageCode: en-us
baseurl: http://example.com/
title: TyDa Rentals
author: Tyler
copyright: Copyright © 2019-2023, Dirk Olbrich, all rights reserved.
params:
  name: Hugo Tailwindcss Starter
  description: A simple bootstraped theme for Hugo, build with Tailwindcss.
  enableDarkToggle: false
  github_user: dirkolbrich
  github_repo: https://github.com/dirkolbrich/hugo-tailwindcss-starter-theme
  github_banner: true
  favicon: favicon.ico
  footer_text: "Welcome to the site"
  matomo:
    url: https://track.xyzz.work
    id: 9
markup:
  highlight:
    style: dracula
