theme = "hugo-tailwindcss-starter-theme"
languageCode = "en-us"
baseurl = "http://example.com/"
title = "Hugo Tailwindcss Starter"

author = "Dirk Olbrich"
copyright = ""

[params]
    github_repo = "https://github.com/dirkolbrich/hugo-tailwindcss-starter-theme"

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
